# Generated by Django 4.2.7 on 2025-10-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_escrow_task_taskapplication_delete_errand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupermarketRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('needed_by_date', models.DateField()),
                ('needed_by_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('shopping_list', models.JSONField(help_text='List of items with optional properties like perishable or substitutions')),
                ('list_image', models.ImageField(blank=True, null=True, upload_to='shopping_lists/')),
                ('drop_off_location', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
