# Generated by Django 4.2.7 on 2025-10-29 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_supermarketrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_urgent', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('sender_phone', models.CharField(max_length=20)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('requires_signature', models.BooleanField(default=False)),
                ('is_fragile', models.BooleanField(default=False)),
                ('special_note', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErrandImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/errand_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('errand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='dashboard.pickupdelivery')),
            ],
        ),
    ]
