# Generated by Django 4.2.7 on 2025-10-29 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_pickupdelivery_errandimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('care_type', models.CharField(blank=True, max_length=255, null=True)),
                ('errand_for', models.CharField(choices=[('me', 'Me'), ('family', 'Family'), ('friend', 'Friend'), ('other', 'Other')], default='me', max_length=50)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('runner_action', models.CharField(blank=True, choices=[('photo', 'Provide photo'), ('video', 'Provide video'), ('text', 'Provide text'), ('other', 'Other')], max_length=50, null=True)),
                ('list_image', models.ImageField(blank=True, null=True, upload_to='caretask_images/')),
                ('frequency', models.CharField(choices=[('one_time', 'One Time'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='one_time', max_length=20)),
                ('days_of_week', models.JSONField(blank=True, help_text="Example: ['Mon', 'Wed', 'Fri']", null=True)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
