# Generated by Django 4.2.7 on 2025-10-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_caretask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('local_micro', 'Local Errand'), ('supermarket_runs', 'Supermarket Runs'), ('pickup_delivery', 'Pickup & Delivery'), ('care_tasks', 'Care Tasks'), ('verify_it', 'Verify It')], max_length=50),
        ),
    ]
