# Generated by Django 4.2.7 on 2025-11-07 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_category_verificationtask_userprofile_errand'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunnerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('Tier 1', 'Tier 1 - Local Errands'), ('Tier 2', 'Tier 2 - City Errands'), ('Tier 3', 'Tier 3 - Pro Runner')], default='Tier 1', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='runner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
