# Generated by Django 4.2.7 on 2025-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalmethod',
            name='method_type',
            field=models.CharField(choices=[('bank', 'Bank'), ('paypal', 'PayPal'), ('mobile_money', 'Mobile Money')], default='bank', max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawalmethod',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalmethod',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
