# Generated by Django 4.2.7 on 2025-10-01 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Kenya', 'Kenya'), ('Togo', 'Togo'), ('Ghana', 'Ghana')], max_length=50)),
                ('document_type', models.CharField(choices=[('National ID', 'National ID'), ("Driver's License", "Driver's License"), ('Passport', 'Passport'), ("Alien Card/Carte Nationale d'Identite", "Alien Card/Carte Nationale d'Identite")], max_length=50)),
                ('document_file', models.FileField(upload_to='identity_documents/')),
                ('verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
