# Generated by Django 4.2.7 on 2025-10-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_permission',
            field=models.CharField(choices=[('while_using_app', 'While Using App'), ('always', 'Always')], default='while_using_app', max_length=20),
        ),
    ]
